name: libpinmame
on:
  push:

jobs:
  build-win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd cmake/libpinmame
          copy CMakeLists_win-x64.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A x64 .
          cmake --build . --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: cmake/libpinmame/lib/libpinmame-*.dll
          
  build-win-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd cmake/libpinmame
          copy CMakeLists_win-x86.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A Win32 .
          cmake --build . --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: win-x86
          path: cmake/libpinmame/lib/libpinmame-*.dll
        
  build-osx-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd cmake/libpinmame
          cp CMakeLists_osx-x64.txt CMakeLists.txt
          cmake -DCMAKE_BUILD_TYPE=Release .
          cmake --build . 
      - uses: actions/upload-artifact@v2
        with:
          name: osx-x64
          path: cmake/libpinmame/lib/libpinmame.*.dylib

  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd cmake/libpinmame
          cp CMakeLists_linux-x64.txt CMakeLists.txt
          cmake -DCMAKE_BUILD_TYPE=Release . 
          cmake --build .
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: cmake/libpinmame/lib/libpinmame.so.*

  dispatch:
    runs-on: ubuntu-latest
    needs: [ build-win-x64, build-win-x86, build-osx-x64, build-linux-x64 ]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_PINMAME_DOTNET }}
          repository: VisualPinball/pinmame-dotnet
          event-type: libpinmame-build
          client-payload: '{"run_id": "${{ github.run_id }}"}'
