name: pinmame32
on:
  push:

jobs:
  build-win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          copy cmake/pinmame32/CMakeLists_win-x64.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A x64 -B build
          cmake --build build --config Release
      - uses: svenstaro/upx-action@v2
        with:
          file: build/bin/PinMAME32.exe
          args: --best --lzma
      - uses: actions/upload-artifact@v2
        with:
          name: PinMAME32-win-x64
          path: build/bin/PinMAME32.exe

  build-win-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - name: Build
        run: |
          copy cmake/pinmame32/CMakeLists_win-x86.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A Win32 -B build
          cmake --build build --config Release
      - uses: svenstaro/upx-action@v2
        with:
          file: build/bin/PinMAME32.exe
          args: --best --lzma
      - uses: actions/upload-artifact@v2
        with:
          name: PinMAME32-win-x86
          path: build/bin/PinMAME32.exe
