name: PPUC
on:
  push:

jobs:
  build:
    name: Build PinMAME/PPUC-${{ matrix.cpu_info }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero, zero2_64]
        include:
          - target: zero
            cpu: arm1176
            cpu_info: cpuinfo/raspberrypi_zero_w
            base_image: raspios_lite:latest
          - target: zero2_64
            cpu: cortex-a53
            cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
            base_image: raspios_lite_arm64:latest
    steps:
      - name: Checkout pinmame
        uses: actions/checkout@v2

      - name: Make in chroot environment
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          copy_repository_path: /opt/pinmame
          commands: |
            sudo -u pi taskset -c 0 /bin/bash cd /opt/pinmame; make -f makefile.ppuc
