name: vpinmame
on:
  push:

jobs:
  build-win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          copy cmake/vpinmame/CMakeLists_win-x64.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A x64 -B build/vpinmame
          cmake --build build/vpinmame --config Release
      - uses: svenstaro/upx-action@v2
        with:
          file: build/vpinmame/Release/VPinMAME64.dll
          args: --best --lzma
      - name: Build Installer
        run: |
          copy cmake/instvpm/CMakeLists_win-x64.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A x64 -B build/instvpm
          cmake --build build/instvpm --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: VPinMAME-win-x64
          path: build/vpinmame/Release/VPinMAME64.dll
      - uses: actions/upload-artifact@v2
        with:
          name: VPinMAME-win-x64
          path: build/instvpm/Release/Setup64.exe
      - uses: actions/upload-artifact@v2
        with:
          name: VPinMAME-win-x64
          path: ext/bass/x64/Bass64.dll

  build-win-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/setup-nasm@v1
      - name: Build
        run: |
          copy cmake/vpinmame/CMakeLists_win-x86.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A Win32 -B build/vpinmame
          cmake --build build/vpinmame --config Release
      - uses: svenstaro/upx-action@v2
        with:
          file: build/vpinmame/Release/VPinMAME.dll
          args: --best --lzma
      - name: Build Installer
        run: |
          copy cmake/instvpm/CMakeLists_win-x86.txt CMakeLists.txt
          cmake -G "Visual Studio 16 2019" -A Win32 -B build/instvpm
          cmake --build build/instvpm --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: VPinMAME-win-x86
          path: build/vpinmame/Release/VPinMAME.dll
      - uses: actions/upload-artifact@v2
        with:
          name: VPinMAME-win-x86
          path: build/instvpm/Release/Setup.exe
      - uses: actions/upload-artifact@v2
        with:
          name: VPinMAME-win-x86
          path: ext/bass/Bass.dll
