name: xpinmame_ppuc
on:
  push:

jobs:
  build:
    name: ${{ matrix.cpu_info }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [zero, zero2_64]
        include:
          - target: zero
            cpu: arm1176
            cpu_info: cpuinfo/raspberrypi_zero_w
            base_image: raspios_lite:latest
          - target: zero2_64
            cpu: cortex-a53
            cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
            base_image: raspios_lite_arm64:latest
    steps:
      - name: Checkout pinmame
        uses: actions/checkout@v2

      - name: Make in chroot environment
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          image_additional_mb: 1024
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          copy_repository_path: /opt/pinmame
          commands: |
            apt-get update -y --allow-releaseinfo-change
            apt-get install --no-install-recommends -y libasound2-dev libsdl2.dev wiringpi
            cd /opt/pinmame
            make -f makefile.ppuc
